[project]
name = "katsastustilastot"
version = "0.1.0"
description = "Add your description here"
classifiers = ["Private :: Do Not Upload"]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "httpx[http2,zstd]>=0.28.1",
    "polars>=1.34.0",
    "ruff>=0.14.5",
]
